cale_passwd: ENC[AES256_GCM,data:qJq3T8LgMW4lIBCkQSAmN5Q9gzVbbrW6avw9SAQArLaGBpm1ea12CtqDxInKwuQXvV7+TCeY/5jfkNb+I+j/7Z589B9q7Ld/ow==,iv:qOp3Tq45q3adrpBWaX0Nral1I9cP3NuZL6jvESo3EsY=,tag:a7hAqxkukpU8IswvGdOMMA==,type:str]
garagefs_rpc_secret: ENC[AES256_GCM,data:wVctAxtnJM8ZUo6ntelSqZADXIoCwe+zmMahZzxEaeSkSl4dwi4HH0+5GlM/S1trdA1YQK6UiiZfjYClSKeJgQ==,iv:uftTb7aiHxShUOJudx0GeC9hOiIlcXRfgeIviosdepo=,tag:PR8iLhqCHy2cvlSJmhIf0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p90f0v3edg8urrk356f8mx47n23xda8yl2xwjqzevpdkq23t6dkstqzdmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZUk2cFM1RUVMN2pHM2U4
            amthYU5aVnkvRHgwNlZrVGZyeHd4T2d6VkJZClovK0x2SGFNNVFBb3FGYUFSK0ZT
            UHUwaHk0VE9GcXpaTFljR3UrbFdUbmcKLS0tIGtrbkdHUGdITFQ4U1Q0d0tmOTZL
            THdLTFpDMW51TE92OWNjS3htNGRJZWMKGU6+cE7bAAvIHX9Yc349vBqPnsKpMe8Y
            XRdOZrQIQ+JAIbiCerKNi5p9nQdi3ykb4imzGGiqAjqPUKw347ZH/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1paagl4g4tf6r6qu0rj5a3rthy4h69vt0enhk87l5vgvd2g8savmsva0pay
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWUNFQWtvL3c0ZTF0QlVC
            eFVGN0pEM1ZSZVFrZW1nMVdYbStFVU53cWhNCmJVdnNJTG9rVktxS09vTGF2eUhE
            eVNZVzgvckN0bVRINFhmNThNZFVzV1kKLS0tIEhYMUhNRXJKdXBmOGQzVHpZTUFo
            YUJhUU1NUVhzWkY3SHZVQ08wUXF3RnMKmw861NM6MZUae0OzdFp1XqoThn/4OM6n
            kKY4GmV0A3R2Mnzl+sJp0xt6Qx0L2riW0cx037jvCtQVfe7p8m7iSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w0fdmrmgu26ez60cpra67jyu2ckcjj9z2sj77rzlguupvkyq0dwqmycyrl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOXJyUThvWkx5MkhpdzVE
            bHRHRUNscFNwclFlcVpQcWNNZXlKU2tzbWxjCnU1SkdVcVB1M1QyTHlIbElMOXRG
            amJoSDc2L0Q0RWVLczdvRUgxZS9ta2sKLS0tIGRRVFlLQWh1THkrU1d2R2Q5dUJW
            TzFGMHdIYkdlVVNKMlBSZ3Qxbno2UE0KAmUFNeSd6VRhzfkaHTVYCZ1RBKbob3va
            9gs0UUh1Qy+X1lO24SiBXPJQgyvinvRSFgE1+wafX+mhCrjlYS13uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T02:57:45Z"
    mac: ENC[AES256_GCM,data:A3jRxlDHAH37Q3eP/+Z6H3rLqoVfJmPNIvkT8YNTNmOcEHRvFZMaOVdArWatEbJUJMuvctwS1RQb9lAf2NGawLh1YbMpoPV0plKbMTzHDciXvVM5X6G44Q1EilD9nTwPho571Y/HZA2JxuqOKhrFDOu41KvT+cb1zX2Ktp9LJJI=,iv:eZOvKyIJKYbJ6Nn9/G/2LwTetpBrJD/gSJumVSLR5wI=,tag:JeiSJXBEp36Bf9kS17MjiQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.10.2
